# lang
export LANG=ja_JP.UTF-8
export SHELL=/usr/local/bin/zsh

# color
export LSCOLORS=ExFxCxdxBxegedabagacad
export LS_COLORS='di=01;34:ln=01;35:so=01;32:ex=01;31:bd=46;34:cd=43;34:su=41;30:sg=46;30:tw=42;30:ow=43;30'

# gnuplot
export GNUTERM=x11

# Homebrew
export PATH=/usr/local/bin:/usr/local/sbin:/usr/local/share:$PATH

# TeXLive
export PATH=/usr/local/texlive/2012/bin/x86_64-darwin:$PATH

# Cabal(Haskell)
export PATH=$HOME/.cabal/bin:$PATH


# rbenv
export PATH=$HOME/.rbenv/shims:$PATH


# nodebrew
export PATH=$HOME/.nodebrew/current/bin:$PATH
export NODEBREW_ROOT=$HOME/.nodebrew


# python
which pythonbrew > /dev/null
if [ $? -eq 0 ]; then
    export PYTHONPATH=$HOME/.pythonbrew/current:$PYTHONPATH
    export WORKON_HOME=$HOME/.virtualenvs
fi


# perlbrev
which perlbrew > /dev/null
if [ $? -eq 0 ]; then
    export PATH=$HOME/perl5/perlbrew/bin/:$PATH
fi


# rbenv
which rbenv > /dev/null
if [ $? -eq 0 ]; then
    export PATH=$HOME/.rbenv/bin:$HOME/.rbenv/shims:$PATH
    eval "$(rbenv init - zsh)"
    source $HOME/.rbenv/completions/rbenv.zsh
fi


# phpenv
which phpenv > /dev/null
if [ $? -eq 0 ]; then
    export PATH=$HOME/.phpenv/bin:$HOME/.phpenv/shims:$PATH
    eval "$(phpenv init - zsh)"
    source $HOME/.phpenv/completions/phpenv.zsh
fi


# JAVA
export JAVA_HOME=/System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home