include_recipe "../cookbooks/browser/default.rb"
include_recipe "../cookbooks/vim/default.rb"
include_recipe "../cookbooks/mail_client/default.rb"
include_recipe "../cookbooks/android/default.rb"
include_recipe "../cookbooks/gcp/default.rb"
